In [1]:
import numpy as np

In [6]:
num_heads = 2
sequence = 3
batch = 1
d = 4

shape = (batch, num_heads, sequence, sequence)
x = np.arange(np.prod(shape)).reshape(shape)

shape = (batch, sequence, num_heads, d)
y = np.arange(np.prod(shape)).reshape(shape)
x.shape, y.shape

((1, 2, 3, 3), (1, 3, 2, 4))

In [7]:
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]])

In [13]:
y

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [23]:
y[0, :, 0]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [24]:
x[0, 0, 0] @ y[0, :, 0]

array([40, 43, 46, 49])

In [12]:
np.einsum('...hsS,...Shd->...shd', x, y)

array([[[[ 40,  43,  46,  49],
         [376, 406, 436, 466]],

        [[112, 124, 136, 148],
         [484, 523, 562, 601]],

        [[184, 205, 226, 247],
         [592, 640, 688, 736]]]])